# BÀI 1: LÀM QUEN VỚI PYTORCH

### Bài 1. Tạo Tensor cơ bản

In [1]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

/usr/local/python/3.14.2/lib/python3.14/site-packages/torch/_subclasses/functional_tensor.py:368: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


### Bài 2. Tạo các Tensor thường dùng

In [2]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.9261, 0.5580, 0.1681, 0.3552],
        [0.2493, 0.3220, 0.7170, 0.1671],
        [0.2261, 0.0300, 0.9911, 0.4650]])
tensor([[ 0.2702, -1.6125,  1.2930,  0.0608],
        [-1.1205, -2.6334,  1.4872,  0.4771],
        [-0.2229,  0.4780,  0.8447,  0.8145]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


### Bài 3. Kiểm tra thông tin Tensor

In [3]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


### Bài 4. Slicing và Indexing

In [4]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-3.8452e-01, -4.1513e-01, -2.1848e-01,  5.0011e-01, -8.1437e-01],
         [-1.4850e+00, -1.3744e+00,  5.2693e-02, -1.1251e-01, -4.1907e-01],
         [-1.1798e+00, -2.8019e+00, -3.6147e-02, -5.0546e-02,  1.3892e+00],
         [ 6.9941e-01,  9.0506e-01,  3.7687e-02, -8.2190e-02, -3.6060e-01]],

        [[-4.6236e-01,  1.4865e+00,  1.7221e+00, -4.0237e-01, -1.7352e+00],
         [ 3.1149e-01,  8.6268e-02, -8.8636e-01,  8.8187e-01, -4.5415e-01],
         [-1.2135e+00, -1.2293e+00, -1.3838e+00, -3.0725e-01,  1.5376e-03],
         [ 6.9793e-01, -9.8023e-01,  2.0814e-01, -3.8939e-01, -5.3385e-01]],

        [[ 1.1290e+00, -3.2525e-01,  1.2040e-01,  1.2351e+00, -6.4242e-01],
         [-9.9228e-01, -3.0600e-01, -1.2549e+00,  8.8955e-01, -3.3368e-01],
         [-4.7051e-01,  7.4421e-01, -2.3205e-01, -3.7972e-01, -2.8707e-01],
         [ 2.4446e-01,  6.8131e-01, -6.6540e-01,  7.2845e-01, -2.2963e-01]]])

Tensor a[1]:
tensor([[-4.6236e-01,  1.4865e+00,  1.7221e+00, -4.

### Bài 5. Reshape và Flatten

In [5]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-0.8100, -0.8169,  0.8628,  0.4281],
        [ 0.0675,  0.2229,  0.1091,  0.4343],
        [ 0.5696,  0.9340,  0.0765, -0.5573]])

Flatten:
tensor([-0.8100, -0.8169,  0.8628,  0.4281,  0.0675,  0.2229,  0.1091,  0.4343,
         0.5696,  0.9340,  0.0765, -0.5573])

Reshape to 3 x 2 x 2:
tensor([[[-0.8100, -0.8169],
         [ 0.8628,  0.4281]],

        [[ 0.0675,  0.2229],
         [ 0.1091,  0.4343]],

        [[ 0.5696,  0.9340],
         [ 0.0765, -0.5573]]])


### Bài 6. Phép toán và nhân ma trận

In [6]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[-0.0721,  1.0552, -0.0238],
        [ 0.9699, -0.6538, -1.1408]])
b:
tensor([[ 0.9550, -0.8446,  0.2145],
        [-0.2372,  1.0619,  0.0335]])

a + b:
tensor([[ 0.8829,  0.2106,  0.1907],
        [ 0.7327,  0.4081, -1.1073]])

a / b:
tensor([[ -0.0755,  -1.2493,  -0.1109],
        [ -4.0885,  -0.6157, -34.0396]])

a^2:
tensor([[5.1998e-03, 1.1135e+00, 5.6645e-04],
        [9.4077e-01, 4.2741e-01, 1.3015e+00]])

Matrix multiplication:
tensor([[-0.9652,  1.1368],
        [ 1.2338, -0.9625]])


### Bài 7. Các hàm thống kê trên Tensor

In [7]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 0.5489,  0.5864,  0.5376, -0.8465],
        [ 0.1584, -0.3899, -1.5218,  0.9525],
        [-1.0893,  0.3169,  0.4239, -1.1514]])

Mean:
tensor([-0.1273,  0.1711, -0.1868, -0.3484])

Standard deviation:
tensor([0.8556, 0.5042, 1.1576, 1.1370])

Cumulative sum:
tensor([[ 0.5489,  0.5864,  0.5376, -0.8465],
        [ 0.7072,  0.1965, -0.9842,  0.1061],
        [-0.3820,  0.5134, -0.5603, -1.0453]])


### Bài 8. Autograd cơ bản

In [8]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


### Bài 9. Gradient Descent tìm hệ số đa thức

In [23]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.8567],
        [ 1.1006],
        [-1.0712]], requires_grad=True)
Learned coefficients:
tensor([[0.9718],
        [1.3967],
        [1.6739]], requires_grad=True)


### Bài 10. Giải hệ phương trình bằng Autograd

In [11]:
import torch

A = torch.tensor(1.0, requires_grad=True)
B = torch.tensor(1.0, requires_grad=True)
C = torch.tensor(1.0, requires_grad=True)
D = torch.tensor(1.0, requires_grad=True)

optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for epoch in range(3000):
    y1 = A + B - 9       # A + B = 9
    y2 = C - D - 1       # C - D = 1
    y3 = A + C - 8       # A + C = 8
    y4 = B - D - 2       # B - D = 2

    loss = y1**2 + y2**2 + y3**2 + y4**2

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print("A =", A.detach().item())
print("B =", B.detach().item())
print("C =", C.detach().item())
print("D =", D.detach().item())
print("Sai số =", loss.detach().item())

A = 4.513519763946533
B = 4.486454963684082
C = 3.486464738845825
D = 2.4864587783813477
Sai số = 8.97728114068741e-10


### Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:

In [12]:
import torch

# 1. Reshape Tensor X
X = torch.arange(24)

print("X ban đầu:", X)
print("X dạng 4 x 6:\n", X.reshape(4, 6))
print("X dạng 2 x 12:\n", X.reshape(2, 12))
print("X dạng 2 x 3 x 4:\n", X.reshape(2, 3, 4))

# 2. Các phép toán trên A và B
A = torch.rand(3, 4) + 0.5
B = torch.rand(3, 4) + 0.5

print("\nA:\n", A)
print("\nB:\n", B)
print("\nA + B:\n", A + B)
print("\nA * B:\n", A * B)
print("\nA / B:\n", A / B)
print("\nTrung bình theo cột:\n", A.mean(dim=0))
print("\nĐộ lệch chuẩn theo cột:\n", A.std(dim=0))

# 3. Autograd với y = 2x^2 + 5x + 3
x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3
y.backward()

dy_dx_autograd = x.grad
dy_dx_manual = 4 * 2 + 5

print("\ny =", y.item())
print("dy/dx bằng autograd =", dy_dx_autograd.item())
print("dy/dx thủ công =", dy_dx_manual)

X ban đầu: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
X dạng 4 x 6:
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
X dạng 2 x 12:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
X dạng 2 x 3 x 4:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

A:
 tensor([[0.9963, 1.2682, 0.5885, 0.6320],
        [0.8074, 1.1341, 0.9901, 1.3964],
        [0.9556, 1.1323, 0.8489, 0.9017]])

B:
 tensor([[0.5223, 0.6689, 0.7939, 1.0185],
        [1.1977, 1.3000, 0.6610, 0.7823],
        [1.1816, 1.4152, 0.8971, 1.3742]])

A + B:
 tensor([[1.5186, 1.9371, 1.3824, 1.6506],
        [2.0051, 2.4341, 1.6511, 2.1787],
        [2.1372, 2.5475, 1.7460, 2.2759]])

A * B